version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=wishtransfert
      - DB_USER=root
      - DB_PASS=root
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  db:
    image: mysql:8.0
    ports:
      - "8889:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wishtransfert
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-allowed-packet=256M
      --innodb-log-file-size=256M
      --innodb-buffer-pool-size=512M
    deploy:
      resources:
        limits:
          memory: 1G

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
  